package gameEnum;

public enum Teams {
    ALL,DIAMONDBACKS,ATHLETICS,BRAVES,ORIOLES,REDSOX,
    CUBS,WHITESOX,REDS,GUARDIANS,ROCKIES,TIGERS,ASTROS,
    ROYALS,ANGELS,DODGERS,MARLINS,BREWERS,TWINS,METS,
    YANKEES,PHILLIES,PIRATES,PADRES,GIANTS,MARINERS,
    CARDINALS,RAYS,RANGERS,BLUEJAYS,NATIONALS
}
